### ISSUE TITLE
javascriptSupport(true) 抓取js生成的数据怎么用啊？

### ISSUE THREAD

**Issue by vgess** [bytegriffin/Get4J#1]
Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: The driver executable does not exist: D:\Get4J-master\bin\chromedriver.exe
	at com.google.common.base.Preconditions.checkState(Preconditions.java:534)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:136)
	at org.openqa.selenium.remote.service.DriverService$Builder.usingDriverExecutable(DriverService.java:265)
	at com.bytegriffin.get4j.net.http.SeleniumEngine.newWebDriver(SeleniumEngine.java:100)
	at com.bytegriffin.get4j.net.http.SeleniumEngine.getWebDriver(SeleniumEngine.java:121)
	at com.bytegriffin.get4j.net.http.SeleniumEngine.getPageContent(SeleniumEngine.java:231)
	at com.bytegriffin.get4j.fetch.SingleFetcher.execute(SingleFetcher.java:38)
	at com.bytegriffin.get4j.core.Chain.execute(Chain.java:13)
	at com.bytegriffin.get4j.core.Worker.run(Worker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vgess** [comment]
下载了chromedriver 也不行

**Comment by bytegriffin** [comment]
你抓取的是哪个网页内容？

**Comment by vgess** [comment]
https://www.jinse.com/lives

**Comment by vgess** [comment]
好的 多谢

**Comment by vgess** [comment]
要是爬取Twitter facebook这些网站 怎么弄




发自网易邮箱大师
在2018年6月20日 22:51，bytegriffin<notifications@github.com> 写道：

Closed #1.

**Comment by vgess** [comment]
您好主要是facebook




发自网易邮箱大师
在2018年7月9日 11:19，郭明海<guomvp@163.com> 写道：
要是爬取Twitter facebook这些网站 怎么弄




发自网易邮箱大师
在2018年6月20日 22:51，bytegriffin<notifications@github.com> 写道：

Closed #1.

**Comment by bytegriffin** [comment]
如果抓取的页面数据是需要登录并且人工验证（比如图片滑动等验证码）的就比较麻烦了，这个就算可以也得写死代码，总之不好弄。
如果抓取的页面是不需要登录就能访问的公共页面，可以试试，不过还得先要找到可以用的http代理才行。

**Comment by vgess** [comment]
就抓取公共帖子 类似这种https://www.facebook.com/groups/CardanoCommunity




发自网易邮箱大师
在2018年7月9日 16:52，bytegriffin<notifications@github.com> 写道：

如果抓取的页面数据是需要登录并且人工验证（比如图片滑动等验证码）的就比较麻烦了，这个就算可以也得写死代码，总之不好弄。
如果抓取的页面是不需要登录就能访问的公共页面，可以试试，不过还得先要找到可以用的http代理才行。

**Comment by bytegriffin** [comment]
简单测了一下好像不行

**Comment by bytegriffin** [comment]
我在处理获取js数据是封装Selenium写的（之前是依赖PhantomJS）。
你可以先单独使用Selenium或者PhantomJS之类的软件看看能否获取到，如果获取不了，那就没招了。

**Comment by vgess** [comment]
好的 谢谢




发自网易邮箱大师
在2018年7月10日 11:40，bytegriffin<notifications@github.com> 写道：

我在处理获取js数据是封装Selenium写的（之前是依赖PhantomJS）。
你可以先单独使用Selenium或者PhantomJS之类的软件看看能否获取到，如果获取不了，那就没招了。

**Comment by vgess** [comment]
javascriptSupport(true) 这个可以用吗 我看YY的那个是false



发自网易邮箱大师
在2018年7月10日 11:40，bytegriffin<notifications@github.com> 写道：

我在处理获取js数据是封装Selenium写的（之前是依赖PhantomJS）。
你可以先单独使用Selenium或者PhantomJS之类的软件看看能否获取到，如果获取不了，那就没招了。

**Comment by bytegriffin** [comment]
javascriptSupport(true) 就是用来打开Selenium功能的。
YY那个例子设置的是false，用来获取YY房间的Http地址的。
如果你想直播YY在线直播源的话，目前版本不支持。
